export const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGIN_GOOGLE_SUCCESS: 'USERS_LOGIN_GOOGLE_SUCCESS',
  LOGIN_GOOGLE_FAILURE: 'USERS_LOGIN_GOOGLE_FAILURE',

  CHECK_CODE_REQUEST: 'USERS_CHECK_CODE_REQUEST',
  CHECK_CODE_SUCCESS: 'USERS_CHECK_CODE_SUCCESS',
  CHECK_CODE_FAILURE: 'USERS_CHECK_CODE_FAILURE',

  GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',

  UPDATE_USER_PROFILE_REQUEST: 'UPDATE_USER_PROFILE_REQUEST',
  UPDATE_USER_PROFILE_SUCESS: 'UPDATE_USER_PROFILE_SUCESS',
  UPDATE_USER_PROFILE_FAILURE: 'UPDATE_USER_PROFILE_FAILURE',

  SENDEMAILFORGOTPASSWORD_REQUEST: 'USERS_FORGOTPASSWORD_REQUEST',
  SENDEMAILFORGOTPASSWORD_SUCCESS: 'USERS_FORGOTPASSWORD_SUCCESS',
  SENDEMAILFORGOTPASSWORD_FAILURE: 'USERS_FORGOTPASSWORD_FAILURE',

  FORGOTPASSWORD_REQUEST: 'USERS_FORGOTPASSWORD_REQUEST',
  FORGOTPASSWORD_SUCCESS: 'USERS_FORGOTPASSWORD_SUCCESS',
  FORGOTPASSWORD_FAILURE: 'USERS_FORGOTPASSWORD_FAILURE',

  GET_HISTORY_SUCCESS: 'USERS_GET_HISTORY_SUCCESS',
  GET_HISTORY_FAILURE: 'USERS_GET_HISTORY_FAILURE',

  GET_LIST_NOTIFICATION_SUCCESS: 'USERS_LIST_NOTIFICATION_SUCCESS',
  GET_LIST_NOTIFICATION_FAILURE: 'USERS_LIST_NOTIFICATION_FAILURE',


  LOGOUT: 'LOGOUT',
};

export const eventConstants = {
  PREPARE_FOR_CREATE_EVENT: 'PREPARE_FOR_CREATE_EVENT',
  PREPARE_FOR_CREATE_EVENT_SUCCESS: 'PREPARE_FOR_CREATE_EVENT_SUCCESS',
  PREPARE_FOR_CREATE_EVENT_FAILURE: 'PREPARE_FOR_CREATE_EVENT_FAILURE',

  STORE_BLOCKS_WHEN_CREATE_EVENT: 'STORE_BLOCKS_WHEN_CREATE_EVENT',

  GET_LIST_EVENT_SUCCESS: 'GET_LIST_EVENT_SUCCESS',
  GET_LIST_EVENT_FAILURE: 'GET_LIST_EVENT_FAILURE',

  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

  DUPLICATE_BLOCK: 'DUPLICATE_BLOCK',
  DELETE_BLOCK: 'DELETE_BLOCK',

  GET_EVENT_DETAIL_SUCCESS: 'GET_EVENT_DETAIL_SUCCESS',
  GET_EVENT_DETAIL_FAILURE: 'GET_EVENT_DETAIL_FAILURE',

  SAVE_EVENT_DETAIL: 'SAVE_EVENT_DETAIL',
  SAVE_EVENT_DETAIL_SUCCESS: 'SAVE_EVENT_DETAIL_SUCCESS',
  SAVE_EVENT_DETAIL_FAILURE: 'SAVE_EVENT_DETAIL_FAILURE',

  SAVE_PAGE: 'SAVE_PAGE',
  UPDATE_PAGE: 'UPDATE_PAGE',

  GET_EVENT_EDIT: 'GET_EVENT_EDIT',
  GET_EVENT_EDIT_FAILURE: 'GET_EVENT_EDIT_FAILURE',
};
