export const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGIN_GOOGLE_SUCCESS: 'USERS_LOGIN_GOOGLE_SUCCESS',
  LOGIN_GOOGLE_FAILURE: 'USERS_LOGIN_GOOGLE_FAILURE',

  CHECK_CODE_REQUEST: 'USERS_CHECK_CODE_REQUEST',
  CHECK_CODE_SUCCESS: 'USERS_CHECK_CODE_SUCCESS',
  CHECK_CODE_FAILURE: 'USERS_CHECK_CODE_FAILURE',

  GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',

  UPDATE_USER_PROFILE_REQUEST: 'UPDATE_USER_PROFILE_REQUEST',
  UPDATE_USER_PROFILE_SUCESS: 'UPDATE_USER_PROFILE_SUCESS',
  UPDATE_USER_PROFILE_FAILURE: 'UPDATE_USER_PROFILE_FAILURE',

  LOGOUT: 'LOGOUT',
};

export const eventConstants = {
  PREPARE_FOR_CREATE_EVENT: 'PREPARE_FOR_CREATE_EVENT',
  STORE_BLOCKS_WHEN_CREATE_EVENT: 'STORE_BLOCKS_WHEN_CREATE_EVENT',
  PREVIEW_DURING_CREATE_EVENT: 'PREVIEW_DURING_CREATE_EVENT',

  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

  DUPLICATE_BLOCK: 'DUPLICATE_BLOCK',
  DELETE_BLOCK: 'DELETE_BLOCK',
};
